[2025-02-03T14:58:58.645+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-03T14:58:58.671+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-02-03T14:58:58.687+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-02-03T14:58:58.688+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-03T14:58:58.736+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-01-24 00:00:00+00:00
[2025-02-03T14:58:58.748+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'extract_weather_data', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmpgfvnt6du']
[2025-02-03T14:58:58.753+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask extract_weather_data
[2025-02-03T14:58:58.760+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-03T14:58:58.764+0000] {standard_task_runner.py:72} INFO - Started process 183 to run task
[2025-02-03T14:58:58.886+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-01-24T00:00:00+00:00 [running]> on host 9591593ff695
[2025-02-03T14:58:59.061+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-02-03T14:58:59.064+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-03T14:59:00.061+0000] {logging_mixin.py:190} INFO - {'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}
[2025-02-03T14:59:00.091+0000] {logging_mixin.py:190} INFO -                                              message
0  Invalid API key. Go to https://docs.rapidapi.c...
[2025-02-03T14:59:00.092+0000] {logging_mixin.py:190} INFO - undexpected error: {e}
[2025-02-03T14:59:00.094+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-03T14:59:00.135+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-03T14:59:00.136+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=extract_weather_data, run_id=scheduled__2025-01-24T00:00:00+00:00, execution_date=20250124T000000, start_date=20250203T145858, end_date=20250203T145900
[2025-02-03T14:59:00.221+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-03T14:59:00.287+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-03T14:59:00.297+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
