[2025-01-26T16:41:04.074+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T16:41:04.105+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-26T16:41:04.136+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-26T16:41:04.138+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-26T16:41:04.218+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2025-01-22 00:00:00+00:00
[2025-01-26T16:41:04.227+0000] {standard_task_runner.py:72} INFO - Started process 644 to run task
[2025-01-26T16:41:04.234+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpehtxb9wd']
[2025-01-26T16:41:04.237+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask insert_into_table
[2025-01-26T16:41:04.369+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-01-22T00:00:00+00:00 [running]> on host e707c27216fc
[2025-01-26T16:41:04.528+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-26T16:41:04.530+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T16:41:04.551+0000] {sql.py:278} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2025-01-22', 'dag_with_postgres_operator_v03')
        
[2025-01-26T16:41:04.568+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:41:04.703+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:41:04.720+0000] {sql.py:553} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2025-01-22', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-01-26T16:41:04.725+0000] {sql.py:562} INFO - Rows affected: 1
[2025-01-26T16:41:04.745+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T16:41:04.746+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250126T164104, end_date=20250126T164104
[2025-01-26T16:41:04.828+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T16:41:04.859+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T16:41:04.861+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
