[2025-01-15T18:14:26.162+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-15T18:14:26.178+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-15T18:14:26.191+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-15T18:14:26.192+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-15T18:14:26.226+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-01-08 00:00:00+00:00
[2025-01-15T18:14:26.243+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt', 'extract_weather_data', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpkiw6yqez']
[2025-01-15T18:14:26.251+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask extract_weather_data
[2025-01-15T18:14:26.251+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-15T18:14:26.252+0000] {standard_task_runner.py:72} INFO - Started process 161 to run task
[2025-01-15T18:14:26.358+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-08T00:00:00+00:00 [running]> on host d596e31c1b5f
[2025-01-15T18:14:26.481+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-01-15T18:14:26.482+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-15T18:14:27.471+0000] {logging_mixin.py:190} INFO - {'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}
[2025-01-15T18:14:27.489+0000] {logging_mixin.py:190} INFO -                                              message
0  Invalid API key. Go to https://docs.rapidapi.c...
[2025-01-15T18:14:27.492+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-15T18:14:27.507+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-15T18:14:27.508+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250115T181426, end_date=20250115T181427
[2025-01-15T18:14:27.590+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-15T18:14:27.612+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-15T18:14:27.613+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
