[2025-02-08T00:57:35.366+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T00:57:35.407+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T00:57:35.429+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T00:57:35.430+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-08T00:57:35.492+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-02-07 00:00:00+00:00
[2025-02-08T00:57:35.510+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'extract_weather_data', 'scheduled__2025-02-07T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmpwgai72wd']
[2025-02-08T00:57:35.517+0000] {standard_task_runner.py:105} INFO - Job 242: Subtask extract_weather_data
[2025-02-08T00:57:35.517+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1763) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T00:57:35.521+0000] {standard_task_runner.py:72} INFO - Started process 1773 to run task
[2025-02-08T00:57:35.650+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-02-07T00:00:00+00:00 [running]> on host a62418b4d22a
[2025-02-08T00:57:35.821+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zalihat' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T00:00:00+00:00'
[2025-02-08T00:57:35.823+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T03:27:52.609+0000] {job.py:229} INFO - Heartbeat recovered after 8981.64 seconds
[2025-02-08T03:28:10.190+0000] {logging_mixin.py:190} INFO - undexpected error: HTTPSConnectionPool(host='weatherapi-com.p.rapidapi.com', port=443): Max retries exceeded with url: /current.json?q=8.950%2C7.0767 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-02-08T03:28:10.329+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T03:28:11.031+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T03:28:11.058+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=extract_weather_data, run_id=scheduled__2025-02-07T00:00:00+00:00, execution_date=20250207T000000, start_date=20250208T005735, end_date=20250208T032811
[2025-02-08T03:28:12.839+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T03:28:14.889+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-08T03:28:15.052+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
