[2025-02-01T20:01:19.420+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T20:01:19.439+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.load_to_postgres scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-01T20:01:19.455+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.load_to_postgres scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-01T20:01:19.456+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-01T20:01:19.497+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-01-30 00:00:00+00:00
[2025-02-01T20:01:19.507+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'load_to_postgres', 'scheduled__2025-01-30T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmpa6b6m7s1']
[2025-02-01T20:01:19.510+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask load_to_postgres
[2025-02-01T20:01:19.512+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=560) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-01T20:01:19.516+0000] {standard_task_runner.py:72} INFO - Started process 570 to run task
[2025-02-01T20:01:19.582+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.load_to_postgres scheduled__2025-01-30T00:00:00+00:00 [running]> on host ba586a51095f
[2025-02-01T20:01:19.676+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-30T00:00:00+00:00'
[2025-02-01T20:01:19.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T20:01:19.720+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-01T20:01:19.734+0000] {sql.py:553} INFO - Running statement: 
    INSERT INTO processed_weather_data (location, region, country, lat, lon, "localtime",
       temperature_c, temperature_f, feelslike_c, feelslike_f, date)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    , parameters: ('Gwagwaldda', 'Federal Capital Territory', 'Nigeria', 8.9414, 7.0919, '2025-01-22 04:49', 23.1, 73.6, 22.6, 72.8, datetime.date(2025, 1, 22))
[2025-02-01T20:01:19.737+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-01T20:01:19.739+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T20:01:19.748+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T20:01:19.750+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=load_to_postgres, run_id=scheduled__2025-01-30T00:00:00+00:00, execution_date=20250130T000000, start_date=20250201T200119, end_date=20250201T200119
[2025-02-01T20:01:19.823+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T20:01:19.845+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T20:01:19.847+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
