[2025-01-03T21:36:47.428+0100] {processor.py:186} INFO - Started process (PID=81237) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:36:47.433+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:36:47.434+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:36:47.434+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:36:47.456+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:36:47.437+0100] {dagbag.py:387} ERROR - Failed to import: /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py", line 2
    from airflow.ope
                    ^
SyntaxError: invalid syntax
[2025-01-03T21:36:47.463+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:36:47.616+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:36:47.616+0100] {workday.py:41} WARNING - Could not import pandas. Holidays will not be considered.
[2025-01-03T21:36:47.648+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.227 seconds
[2025-01-03T21:38:50.396+0100] {processor.py:186} INFO - Started process (PID=81912) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:38:50.401+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:38:50.402+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:38:50.401+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:38:50.421+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:38:50.405+0100] {dagbag.py:387} ERROR - Failed to import: /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py", line 2
    from airflow.ope
                    ^
SyntaxError: invalid syntax
[2025-01-03T21:38:50.427+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:38:50.563+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:38:50.563+0100] {workday.py:41} WARNING - Could not import pandas. Holidays will not be considered.
[2025-01-03T21:38:50.589+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.202 seconds
[2025-01-03T21:41:55.115+0100] {processor.py:186} INFO - Started process (PID=83620) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:41:55.120+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:41:55.121+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:41:55.121+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:41:55.140+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:41:55.124+0100] {dagbag.py:387} ERROR - Failed to import: /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py", line 2
    from airflow.ope
                    ^
SyntaxError: invalid syntax
[2025-01-03T21:41:55.146+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:41:55.279+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:41:55.279+0100] {workday.py:41} WARNING - Could not import pandas. Holidays will not be considered.
[2025-01-03T21:41:55.318+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.210 seconds
[2025-01-03T21:45:01.389+0100] {processor.py:186} INFO - Started process (PID=84770) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:45:01.393+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:45:01.394+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:45:01.394+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:45:01.440+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:45:01.426+0100] {dagbag.py:387} ERROR - Failed to import: /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py", line 6, in <module>
    from tasks.extract import extract_weather_data
ModuleNotFoundError: No module named 'tasks'
[2025-01-03T21:45:01.445+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:45:01.577+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:45:01.577+0100] {workday.py:41} WARNING - Could not import pandas. Holidays will not be considered.
[2025-01-03T21:45:01.603+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.222 seconds
[2025-01-03T21:48:14.053+0100] {processor.py:186} INFO - Started process (PID=86416) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:48:14.058+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:48:14.059+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.058+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:48:14.320+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:48:14.598+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.597+0100] {override.py:1912} INFO - Created Permission View: can delete on DAG:Temp_elt
[2025-01-03T21:48:14.610+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.610+0100] {override.py:1912} INFO - Created Permission View: can read on DAG:Temp_elt
[2025-01-03T21:48:14.619+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.619+0100] {override.py:1912} INFO - Created Permission View: can edit on DAG:Temp_elt
[2025-01-03T21:48:14.634+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.634+0100] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:Temp_elt
[2025-01-03T21:48:14.642+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.642+0100] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:Temp_elt
[2025-01-03T21:48:14.654+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.654+0100] {override.py:1912} INFO - Created Permission View: can read on DAG Run:Temp_elt
[2025-01-03T21:48:14.662+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.661+0100] {override.py:1912} INFO - Created Permission View: can create on DAG Run:Temp_elt
[2025-01-03T21:48:14.662+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.662+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-03T21:48:14.678+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.678+0100] {dag.py:3262} INFO - Creating ORM DAG for Temp_elt
[2025-01-03T21:48:14.690+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:48:14.690+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-03 00:00:00+00:00, run_after=2025-01-04 00:00:00+00:00
[2025-01-03T21:48:14.711+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.666 seconds
[2025-01-03T21:50:44.351+0100] {processor.py:186} INFO - Started process (PID=87236) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:50:44.356+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:50:44.357+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.357+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:50:44.636+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:50:44.830+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.830+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-03T20:50:33.055586+00:00', 'Hostname': 'macbookpro'}
[2025-01-03T21:50:44.844+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.843+0100] {workday.py:41} WARNING - Could not import pandas. Holidays will not be considered.
[2025-01-03T21:50:44.893+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-03T21:50:44.893+0100] {logging_mixin.py:190} INFO - Task start:2025-01-03 20:50:41.027562+00:00 end:2025-01-03 20:50:44.888780+00:00 duration:3.861218
[2025-01-03T21:50:44.893+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-03 20:50:33.055586+00:00: manual__2025-01-03T20:50:33.055586+00:00, state:running, queued_at: 2025-01-03 20:50:33.076904+00:00. externally triggered: True>
[2025-01-03T21:50:44.894+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-03T20:50:33.055586+00:00', 'Hostname': 'macbookpro'}
[2025-01-03T21:50:44.894+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.894+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=manual__2025-01-03T20:50:33.055586+00:00, execution_date=20250103T205033, start_date=20250103T205041, end_date=20250103T205044
[2025-01-03T21:50:44.905+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.905+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data manual__2025-01-03T20:50:33.055586+00:00 [up_for_retry]> in state up_for_retry
[2025-01-03T21:50:44.927+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.926+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-03T21:50:44.948+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:44.948+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-03 00:00:00+00:00, run_after=2025-01-04 00:00:00+00:00
[2025-01-03T21:50:44.967+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.625 seconds
[2025-01-03T21:51:24.663+0100] {processor.py:186} INFO - Started process (PID=87480) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:51:24.668+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-03T21:51:24.670+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:51:24.670+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:51:24.921+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-03T21:51:25.104+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:51:25.103+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-03T21:51:25.127+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:51:25.127+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-03 00:00:00+00:00, run_after=2025-01-04 00:00:00+00:00
[2025-01-03T21:51:25.150+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 0.494 seconds
