[2025-01-15T18:14:56.397+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-15T18:14:56.408+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-01-15T18:14:56.415+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-13T00:00:00+00:00 [queued]>
[2025-01-15T18:14:56.415+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-15T18:14:56.438+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-01-13 00:00:00+00:00
[2025-01-15T18:14:56.446+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt', 'extract_weather_data', 'scheduled__2025-01-13T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpx5uewed2']
[2025-01-15T18:14:56.448+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask extract_weather_data
[2025-01-15T18:14:56.449+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-15T18:14:56.450+0000] {standard_task_runner.py:72} INFO - Started process 224 to run task
[2025-01-15T18:14:56.501+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-13T00:00:00+00:00 [running]> on host d596e31c1b5f
[2025-01-15T18:14:56.582+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T00:00:00+00:00'
[2025-01-15T18:14:56.583+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-15T18:14:57.550+0000] {logging_mixin.py:190} INFO - {'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}
[2025-01-15T18:14:57.569+0000] {logging_mixin.py:190} INFO -                                              message
0  Invalid API key. Go to https://docs.rapidapi.c...
[2025-01-15T18:14:57.572+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-15T18:14:57.584+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-15T18:14:57.586+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-13T00:00:00+00:00, execution_date=20250113T000000, start_date=20250115T181456, end_date=20250115T181457
[2025-01-15T18:14:57.619+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-15T18:14:57.641+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-15T18:14:57.642+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
