[2025-02-01T19:58:01.950+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T19:58:01.963+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-01-26T00:00:00+00:00 [queued]>
[2025-02-01T19:58:01.972+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-01-26T00:00:00+00:00 [queued]>
[2025-02-01T19:58:01.972+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-01T19:58:02.001+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-01-26 00:00:00+00:00
[2025-02-01T19:58:02.008+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'extract_weather_data', 'scheduled__2025-01-26T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmpttcc67tv']
[2025-02-01T19:58:02.011+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask extract_weather_data
[2025-02-01T19:58:02.012+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-01T19:58:02.013+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2025-02-01T19:58:02.070+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.extract_weather_data scheduled__2025-01-26T00:00:00+00:00 [running]> on host ba586a51095f
[2025-02-01T19:58:02.154+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-26T00:00:00+00:00'
[2025-02-01T19:58:02.155+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T19:58:04.056+0000] {logging_mixin.py:190} INFO - {'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}
[2025-02-01T19:58:04.074+0000] {logging_mixin.py:190} INFO -                                              message
0  Invalid API key. Go to https://docs.rapidapi.c...
[2025-02-01T19:58:04.075+0000] {logging_mixin.py:190} INFO - undexpected error: {e}
[2025-02-01T19:58:04.076+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T19:58:04.084+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T19:58:04.085+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=extract_weather_data, run_id=scheduled__2025-01-26T00:00:00+00:00, execution_date=20250126T000000, start_date=20250201T195801, end_date=20250201T195804
[2025-02-01T19:58:04.127+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T19:58:04.156+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-01T19:58:04.161+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
