[2025-01-26T16:41:56.539+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T16:41:56.560+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-26T16:41:56.575+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-26T16:41:56.576+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2025-01-26T16:41:56.635+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2025-01-23 00:00:00+00:00
[2025-01-26T16:41:56.643+0000] {standard_task_runner.py:72} INFO - Started process 98 to run task
[2025-01-26T16:41:56.652+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmppvybe872']
[2025-01-26T16:41:56.657+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask insert_into_table
[2025-01-26T16:41:56.783+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-01-23T00:00:00+00:00 [running]> on host b597abfab341
[2025-01-26T16:41:56.973+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-01-26T16:41:56.975+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T16:41:57.007+0000] {sql.py:278} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2025-01-23', 'dag_with_postgres_operator_v03')
        
[2025-01-26T16:41:57.028+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:41:57.173+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:41:57.191+0000] {sql.py:553} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2025-01-23', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-01-26T16:41:57.195+0000] {sql.py:562} INFO - Rows affected: 1
[2025-01-26T16:41:57.219+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T16:41:57.221+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250126T164156, end_date=20250126T164157
[2025-01-26T16:41:57.291+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T16:41:57.320+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T16:41:57.321+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
